
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaochuangtianxia/myremoteconfig.git
          search-paths: direct,mydirect
eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka